version: "3"
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    env_file:
      - "server.cfg"
      - "server.env"
    networks:
      - "mc-smp-net"
    volumes:
      - "./data:/data"
networks:
  mc-smp-net:
    driver: bridge
